projectwebdev/Pages/Collecties/Delete.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using projectwebdev.Models;
using projectwebdev.Services;

namespace projectwebdev.Pages.Collecties
{
    [Authorize]

    public class DeleteModel : PageModel
    {
        private readonly ICollectieRepository collectieRepository;

        public DeleteModel(ICollectieRepository collectieRepository)
        {
            this.collectieRepository = collectieRepository;
        }
        
        [BindProperty]
        public Collectie Collectie { get; set; }

        public IActionResult OnGet(int collectieid)
        {
            Collectie = collectieRepository.GetCollectie(collectieid);

            if (Collectie == null)
            {
                return RedirectToPage("/NietGevonden");
            }

            return Page();
        }

        public IActionResult OnPost()
        {
            Collectie deletedCollectie = collectieRepository.Delete(Collectie.CollectieID);

            if (deletedCollectie == null)
            {
                return RedirectToPage("/NietGevonden");
            }

            return RedirectToPage("Index");
        }
    }
}

projectwebdev/Pages/Collecties/Detail.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using projectwebdev.Models;
using projectwebdev.Services;

namespace projectwebdev.Pages.Collecties
{
    public class DetailModel : PageModel
    {
        private readonly ICollectieRepository collectieRepository;

        public DetailModel(ICollectieRepository collectieRepository)
        {
            this.collectieRepository = collectieRepository;
        }

        public Collectie Collectie { get; private set; }

        public void OnGet(int collectieid)
        {
            Collectie = collectieRepository.GetCollectie(collectieid);
        }

        
    }
}
    
    
    
        
        

projectwebdev/Pages/Collecties/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using projectwebdev.Models;
using projectwebdev.Services;

namespace projectwebdev.Pages.Collecties
{
    [Authorize]

    public class EditModel : PageModel
    {
        private readonly ICollectieRepository collectieRepository;
        private readonly IWebHostEnvironment webHostEnvironment;

        public EditModel(ICollectieRepository collectieRepository, IWebHostEnvironment webHostEnvironment)
        {
            this.collectieRepository = collectieRepository;
            this.webHostEnvironment = webHostEnvironment;
        }

        [BindProperty]
        public Collectie Collectie { get; set; }

        public IActionResult OnGet(int? collectieid)
        {
            if (collectieid.HasValue)
            {
                Collectie = collectieRepository.GetCollectie(collectieid.Value);
            }
            else
            {
                Collectie = new Collectie();
            }

            if (Collectie == null)
            {
                return RedirectToPage("/NietGevonden");
            }

            return Page();
        }

        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                if (Collectie.CollectieID > 0)
                {
                    Collectie = collectieRepository.Update(Collectie);
                }
                else
                {
                    Collectie = collectieRepository.Add(Collectie);
                }

                return RedirectToPage("Index");
            }

            return Page();
        }
    }
}

projectwebdev/Pages/Collecties/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using projectwebdev.Models;
using projectwebdev.Services;

namespace projectwebdev.Pages
{
    [Authorize]
    public class CollectiesModel : PageModel
    {
        private readonly ICollectieRepository collectieRepository;
        
        public IEnumerable<Collectie> Collecties { get; set; }

        public CollectiesModel(ICollectieRepository collectieRepository)
        {
            this.collectieRepository = collectieRepository;
        }

        public void OnGet()
        {
            Collecties = collectieRepository.GetAllCollecties();
        }
    }
}

projectwebdev/Pages/Collecties/StripToevoegen.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using projectwebdev.Models;
using projectwebdev.Services;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization;

namespace projectwebdev.Pages.Collecties
{
    [Authorize]

    public class StripToevoegen : PageModel
    {
        public IEnumerable<StripboekCollectie> StripboekCollecties
        {
           get
            {
                return new StripboekCollectieRepository().Get();
            }
        }

        public void OnGet()
        {
        }

        public void OnPostDelete(int stripboekId)
        {
            new StripboekCollectieRepository().Delete(stripboekId);
        }
        
        [BindProperty]
        public StripboekCollectie NewStripboekCollectie { get; set; }

        public IActionResult OnPostCreate()
        {
            if (ModelState.IsValid)
            {
                new StripboekCollectieRepository().Add(NewStripboekCollectie);
            }

            return Page();
        }
        
    }
}

projectwebdev/Pages/Collecties/Toevoegen.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using projectwebdev.Models;
using projectwebdev.Services;

namespace projectwebdev.Pages.Collecties
{
    [Authorize]
    public class CollectiesModel : PageModel
    {
        private readonly ICollectieRepository collectieRepository;
        
        public IEnumerable<Collectie> Collecties { get; set; }

        public CollectiesModel(ICollectieRepository collectieRepository)
        {
            this.collectieRepository = collectieRepository;
        }
        

        public void OnGet()
        {
            Collecties = collectieRepository.GetAllCollecties();
        }

        public IActionResult OnPost(int CollectieID)
        {
            
        }
    }

}

projectwebdev/Pages/Titels/Delete.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using projectwebdev.Models;
using projectwebdev.Services;

namespace projectwebdev.Pages.Titels
{
    [Authorize(Roles = "Administrator")]
    public class DeleteModel : PageModel
    {
        private readonly IStripboekRepository stripboekRepository;
        public DeleteModel(IStripboekRepository stripboekRepository)
        {
            this.stripboekRepository = stripboekRepository;
        }

        [BindProperty]
        public Stripboek Stripboek { get; set; }
        public IActionResult OnGet(int id)
        {
            Stripboek = stripboekRepository.GetStripboek(id);

            if(Stripboek == null)
            {
                return RedirectToPage("/NietGevonden");
            }

            return Page();
        }

        public IActionResult OnPost()
        {
            Stripboek deletedStripboek = stripboekRepository.Delete(Stripboek.Id);

            if (deletedStripboek == null)
            {
                return RedirectToPage("/NietGevonden");
            }

            return RedirectToPage("Index");
        }
    }
}

projectwebdev/Pages/Titels/Detail.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using projectwebdev.Models;
using projectwebdev.Services;

namespace projectwebdev.Pages.Titels
{
    public class DetailModel : PageModel
    {
        private readonly IStripboekRepository stripboekRepository;
        public DetailModel(IStripboekRepository stripboekRepository)
        {
            this.stripboekRepository = stripboekRepository;
        }

        public Stripboek Stripboek { get; private set; }

        public void OnGet(int id)
        {
            Stripboek = stripboekRepository.GetStripboek(id);
        }
    }
}

projectwebdev/Pages/Titels/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using projectwebdev.Models;
using projectwebdev.Services;

namespace projectwebdev.Pages.Titels
{
    [Authorize(Roles = "Administrator")]
    public class EditModel : PageModel
    {
        private readonly IStripboekRepository stripboekRepository;
        private readonly IWebHostEnvironment webHostEnvironment;

        public EditModel(IStripboekRepository stripboekRepository, IWebHostEnvironment webHostEnvironment)
        {
            this.stripboekRepository = stripboekRepository;
            this.webHostEnvironment = webHostEnvironment;
        }

        [BindProperty]
        public Stripboek Stripboek { get; set; }

        [BindProperty]
        public IFormFile? Cover { get; set; }
        
        public IActionResult OnGet(int? id)
        {
            if(id.HasValue)
            {
                Stripboek = stripboekRepository.GetStripboek(id.Value);
            }
            else
            {
                Stripboek = new Stripboek();
            }

            if (Stripboek == null)
            {
                return RedirectToPage("/NietGevonden");
            }

            return Page();
        }

        public IActionResult OnPost()
        {
            if (ModelState.IsValid) {
                if (Cover != null)
                {
                    if (Stripboek.CoverImageUrl != null)
                    {
                        string filePath = Path.Combine(webHostEnvironment.WebRootPath, "images", Stripboek.CoverImageUrl);
                        System.IO.File.Delete(filePath);
                    }
                    Stripboek.CoverImageUrl = ProcessUploadedFile();
                }

                if (Stripboek.Id > 0)
                {
                    Stripboek = stripboekRepository.Update(Stripboek);
                }
                else
                {
                    Stripboek = stripboekRepository.Add(Stripboek);
                }

                return RedirectToPage("Index");
            }

            return Page();
        }

        private string ProcessUploadedFile()
        {
            string uniqueFileName = null;

            if (Cover != null)
            {
                string uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + Cover.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    Cover.CopyTo(fileStream);
                }
            }

            return uniqueFileName;
        }
    }
}

projectwebdev/Pages/Collecties/Delete.cshtml
@page "{collectieid:min(1)}"
@model projectwebdev.Pages.Collecties.DeleteModel
@{
}

<h1>Bevestig verwijderen</h1>

<div class="alert alert-danger">
	<h5>Weet je zeker dat je - @Model.Collectie.CollectieNaam - wilt verwijderen?</h5>
	<form method="post">
		<button class="btn-primary btn-danger">Ja</button>
		<a class="btn" asp-page="/Collecties/Index">Annuleren</a>
	</form>
</div>

projectwebdev/Pages/Collecties/Detail.cshtml
@page "/collecties/view/{collectieid:min(1)}"
@model projectwebdev.Pages.Collecties.DetailModel
@{
    ViewData["Title"] = "Collecties";
}

<div>
    <h1 style="font-weight: bold">@Model.Collectie.CollectieNaam</h1>
    <br/>
</div>

<div class="container">
	<h5 style="font-weight: bold">Overzicht</h5>
	<hr/>
	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra vulputate placerat. Pellentesque at tincidunt leo. Sed volutpat odio nec pharetra tempor. Integer a tincidunt turpis. Etiam a leo tortor. Morbi feugiat tempus metus eget varius. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam imperdiet pharetra justo sit amet facilisis. In hac habitasse platea dictumst. Ut quis dapibus tortor.</p>
</div>


<a asp-page="/Collecties/StripToevoegen" class="btn">Strip toevoegen</a>
<a asp-page="/Collecties/Edit" asp-route-collectieid="@Model.Collectie.CollectieID" class="btn">Bewerken</a>
<a asp-page="/Collecties/Delete" asp-route-collectieid="@Model.Collectie.CollectieID" class="btn btn-danger">Verwijderen</a>

projectwebdev/Pages/Collecties/Edit.cshtml
@page "{collectieid:min(1)?}"
@model projectwebdev.Pages.Collecties.EditModel
@{
    ViewData["Title"] = "Collecties";
    var pageHeader = Model.Collectie.CollectieID > 0 ? "Bewerken" : "Toevoegen";
}

<h1>@pageHeader</h1>
<div class="row">
    <div class="col-lg-6">
        <div class="edit-form">
            <form method="post" enctype="multipart/form-data">
                <input hidden asp-for="Collectie.CollectieID" />

                <div class="form-floating">
                    <label asp-for="Collectie.CollectieNaam"></label>
                    <input asp-for="Collectie.CollectieNaam" placeholder="Collectie Naam" />
                    <span asp-validation-for="Collectie.CollectieNaam" class="text-danger"></span>
                </div>

                <div class="buttons">
                    <button type="submit" class="btn btn-primary">Opslaan</button>
                    <a asp-page="/collecties/index" class="btn">Annuleren</a>
                </div>
            </form>
        </div>
    </div>
    
</div>

projectwebdev/Pages/Collecties/Index.cshtml
@page "/Collecties"
@using projectwebdev.Models
@model projectwebdev.Pages.CollectiesModel
@{
    ViewData["Title"] = "Collecties";
}
<a asp-page="/Collecties/Edit" class="btn">Collectie aanmaken</a>
<div class="row">
    @foreach (var collectie in Model.Collecties)
    {
        <div class="col-12 col-sm-6 col-md-4 col-lg-3 col-xl-2">
            <div class="collectie-wrapper">
                <a asp-page="/collecties/detail" asp-route-collectieid="@collectie.CollectieID">
                    <h3>@collectie.CollectieNaam</h3>
                </a>
            </div>
        </div>
    }
</div>

projectwebdev/Pages/Collecties/StripToevoegen.cshtml
@page
@using NuGet.Protocol
@model projectwebdev.Pages.Collecties.StripToevoegen

@{
    ViewData["Title"] = "StripCollectie Pagina";
}


<h1>Collectie Pagina</h1>
<hr/>

<div class="container">
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 col-xl-2">
        <div class="collectie-wrapper">
            <ul>
                @foreach (var stripboekcollectie in @Model.StripboekCollecties)
                {
                    <li>@stripboekcollectie.Titel == @stripboekcollectie.Schrijver
                        <form method="post">
                            <button type="submit" asp-page-handler="Delete" asp-route-stripboekId="@stripboekcollectie.StripboekID" class="btn btn-danger">Verwijderen</button>
                        </form>
                    </li>
                }
            </ul>
            </div>
    </div> 
     <hr/>
        <div>
            <form method="post" asp-page-handler="Create">
                Titel: <input asp-for="NewStripboekCollectie.Titel"/>
                <span asp-validation-for="NewStripboekCollectie.Titel"></span>
                <br/>
                Schrijver: <input asp-for="NewStripboekCollectie.Schrijver"/>
                <span asp-validation-for="NewStripboekCollectie.Schrijver"></span>
                <br/>
                Tekenaar: <input asp-for="NewStripboekCollectie.Schrijver"/>
                <span asp-validation-for="NewStripboekCollectie.Schrijver"></span>
                <br/>
                Aantal bladzijden: <input asp-for="NewStripboekCollectie.Aantal_Blz"/>
                <span asp-validation-for="NewStripboekCollectie.Aantal_Blz"></span>
                <br/>
                ISBN: <input asp-for="NewStripboekCollectie.ISBN"/>
                <span asp-validation-for="NewStripboekCollectie.ISBN"></span>
                <br/>
                <button type="submit" class="btn btn-primary">Toevoegen</button>
            </form>
        </div>
</div>        
            
  

projectwebdev/Pages/Collecties/Toevoegen.cshtml
@page "{id:min(1)?}"
@using projectwebdev.Models
@model projectwebdev.Pages.CollectiesModel

@{
    ViewData["Title"] = "Collecties";
}

<h1>Aan welke collectie wilt u het stripboek toevoegen?</h1>

<div class="row">
    @foreach (var collectie in Model.Collecties)
    {
        <form method="post">
            <div class="col-12 col-sm-6 col-md-4 col-lg-3 col-xl-2">
                <div class="collectie-wrapper">
                    <button type="submit" asp-page="/collecties/detail" asp-route-collectieid="@collectie.CollectieID" class="btn btn-primary">
                        @collectie.CollectieNaam
                    </button>
                </div>
            </div>
        </form>
    }
</div>


 